#!/usr/bin/env bash                                                                                                                                    

set -u -o pipefail -o noclobber

totaal=0

while IFS=' ' read -r col1 _ _ _; do
    count=$(cut -d ' ' -f 4 "$1" | grep -wc "$col1")
    (( totaal += col1 * count ))
done < "$1"                                                                                                                                        

echo "$totaal"

