#!/bin/bash

input=$1
tempfile0=$(mktemp)
tempfile=$(mktemp)
tempfile2=$(mktemp)

sed -E "s/one/o1e/g" "$input" | sed -E "s/two/t2o/g" | sed -E "s/three/t3e/g" | sed -E "s/four/4/g" | \
 sed -E "s/five/f5/g" | sed -E "s/six/s6/g" | sed -E "s/seven/s7n/g" | sed -E "s/eight/e8t/g" | sed -E "s/nine/n9/g" > "$tempfile0"

sed 's/[a-zA-Z]*//g' "$tempfile0" > "$tempfile"

#paste -d' ' "$input" "$tempfile0"

while read -r line; do
        if [ ${#line} -gt 2 ]; then
        number="${line:0:1}${line: -1}"

        elif [ ${#line} -lt 2 ]; then
        number="${line:0:1}${line:0:1}"

        else
        number="$line"

        fi
        echo "$number" >> "$tempfile2"
done < "$tempfile"

paste -sd+ "$tempfile2" | bc

rm "$tempfile0"
rm "$tempfile"
rm "$tempfile2"
